spring:
  profiles: development

  cloud:
    stream:
      bindings:
        paymentRequestChannel:
          destination: userPayment
          binder: kafka
          group: paymentConsumer
        processSale:
          destination: userSale
          binder: kafka
          group: saleProducer
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true
server:
  port: 8081

---

spring:
  profiles: production

  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/user_db?autoReconnect=true&useSSL=false
    username: root
    password: root
  cloud:
    stream:
      bindings:
        paymentRequestChannel:
          destination: userPayment
          binder: kafka
          group: paymentConsumer
        processSale:
          destination: userSale
          binder: kafka
          group: saleProducer
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true

server:
  port: 8081


