version: '3.3'

services:

  mysql:
    image: mysql/mysql-server:5.7
    container_name: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=test
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root

  zookeeper:
    image: wurstmeister/zookeeper:3.4.6
    ports:
      - "2181:2181"

  kafka:
    image: wurstmeister/kafka:2.11-2.0.0
    links:
      - zookeeper
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ADVERTISED_PORT: 9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: "order:5:1"

  user-service:
    build:
      context: ./user
      dockerfile: Dockerfile
    depends_on:
      - mysql
      - kafka
    ports:
      - 8081:8081
    environment:
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092

  stock-service:
    build:
      context: ./future-stock
      dockerfile: Dockerfile
    container_name: stock-service
    depends_on:
      - kafka
    ports:
      - 8082:8082
    environment:
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092

  angular-front:
    build:
      context: ./client-front
      dockerfile: Dockerfile
    ports:
      - 4200:4200




